# Generated by Django 3.0 on 2021-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.IntegerField()),
                ('rollno', models.CharField(max_length=10)),
                ('addres', models.TextField(null=True)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=6)),
                ('dob', models.DateField()),
                ('timet', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.FloatField(null=True)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
